eighties = {
    "The Princess Bride": "My name is Inigo Montoya. You killed my father. Prepare to die.",
    "Back to the Future": "Roads? Where we're going, we don't need roads.",
    "Ferris Bueller's Day Off": "Life moves pretty fast. You don't stop and look around once in a while, you could miss it.",
    "Carpe diem boys. Seize the day!": "Dead Poets Society",
    "The Shining": "Here's Johnny!",
    "Star Wars": "Do or do not. There is no try.",
    "The Breakfast Club": "We are all pretty bizarre. Some of us are just better at hiding it, that's all.",
    "The Princess Bride": "Death cannot stop true love. All it can do is delay it for a while.",
    "Beverly Hills Cop": "Before I go, I just want you two to know something, alright? The supercop story... was working. Okay? It was working, and you guys just messed it up.",
    "The Terminator": "I'll be back.",
    "Ferris Bueller's Day Off": "You're not dying. You just can't think of anything good to do.",
    "Scarface": "Say hello to my little friend.",
    "Scarface": "Me? I always tell the truth. Even when I lie! So say goodnight to the bad guy!",
    "Wall Street": "Greed, for lack of a better word, is good.",
    "Pretty In Pink": "If someone doesn't believe in me, I can't believe in them.",
    "Uncle Buck": "Here... Take this quarter. Go downtown and have a rat naw that thing off your face.",
    "The Breakfast Club": "Does Barry Manilow know that you raid his wardrobe?",
    "Sixteen Candles": "I want a serious girlfriend. Somebody I can love that's gonna love me back. Is that psycho?",
    "Fast Times at Ridgemont High": "I've been thinking about this, Mr. Hand. If I'm here and you're here, doesn't that make it our time?",
    "Top Gun": "I feel the need... the need for speed.",
    "The Karate Kid": "Wax on, wax off.",
    "Die Hard": "Come out the coast, we'll get together, have a few laughs",
    "Field of Dreams": "If you build it, he will come.",
    "When Harry Met Sally": "I'll have what she's having.",
    "A Christmas Story": "You'll shoot your eye out, kid."
}

nineties = {
    "A Few Good Men": "You can't handle the truth!",
    "Forrest Gump": "Life is like a box of chocolates; you never know what you're gonna get.",
    "The Shawshank Redepmtion": "Hope is a good thing, maybe the best of things. And no good thing ever dies.",
    "Apollo 13": "Houston, we have a problem.",
    "Jerry Maguire": "Show me the money!",
    "Good Will Hunting": "Do you like apples? ...Well I got her number. How do you like them apples?",
    "Toy Story": "To infinity and beyond!",
    "Goodfellas": "I ordered some spaghetti with marinara sauce, and I got egg noodles and ketchup. I'm an average nobody.",
    "Jurassic Park": 'Spare no expense!',
    "The Big Lebowski": "He peed on your rug, dude.",
    "The Lion King": "Everything the light touches is our kingdom.",
    "Scream": "What's your favorite scary movie?",
    "Dumb and Dumber": "So you're telling me there's a chance?",
    "Friday": "Bye, Felisha!",
    "The Sandlot": "You're killin me, Smalls!",
    "Titanic": "I'm the king of the world!",
    "The Waterboy": "Now that's some high quality H2O.",
    "The Sixth Sense": "I see dead people.",
    "Braveheart": "Your heart is free. Learn to follow it.",
    "The Truman Show": "Good morning! Oh and in case I don't see you, good afternoon, good evening and goodnight!",
    "Goodfellas": "Never rat on your friends and always keep your mouth shut.",
    "Babe": "That'll do, pig. That'll do.",
    "Rush Hour": "Do you understand the words that are coming out of my mouth!?",
    "Dazed and Confused": "That's what I love about these high school girls, man. I get older, they stay the same age.",
    "The Mask": "It's party time! P-A-R-T-Why!? Because I gotta!",
}

thousands = {
    "Cast Away": "Wilson!",
    "Finding Nemo": "Just keep swimming.",
    "300": "This is Sparta!",
    "Idiocracy": "Electrolytes, it's what plants crave!",
    "Dodgeball": "If you can dodge a wrench, you can dodge a ball.",
    "40 Year Old Virgin": "You know when you grab a woman's breast, and it feels like a bag of sand?",
    "Joe Dirt": "Life's a garden; dig it.",
    "Superbad": "Take off your vest. You look like Aladdin.",
    "Spider Man": "With great power, comes great responsibility.",
    "The Dark Knight": "Why so serious?",
    "No Country for Old Men": "What business is it of yours where I come from, friendo?",
    "Gran Torino": "Get off my lawn.",
    "Zoolander": "What is this!? A center for ants!? How can we be expected to teach children to learn how to read if they can't even fit inside the building?",
    "Almost Famous": "I am a golden god!",
    "Meet the Parents": "I have nipples, Greg. Could you milk me?",
    "The Lord of the Rings": "You shall not pass!",
    "Pirates of the Caribbean": "You will always remember this as the day that you almost caught Captain Jack Sparrow!",
    "Saw": "You don't know me, but I know you. I want to play a game.",
    "Wedding Crashers": "Why don't you try getting jacked off under the table in front of the whole damn family, then have some real problems.",
    "The Departed": "When I was your age, they would say we could become cops or criminals. What I'm saying is this... When you're facing a loaded gun, what's the difference?",
    "The Departed": "I'm the guy who does his job. You must be the other guy.",
    "No Country for Old Men": "What's the most you ever lost on a coin toss?",
    "The Dark Knight": "Do you wanna know how I got these scars?",
    "Taken": "I will look for you. I will find you and I will kill you.",
    "Tropic Thunder": "I know who I am! I'm a dude playing a dude disguised as another dude!"
}

tenthousands = {
    "Bridesmaids": "Help me! I'm poor.",
    "Wolf of Wall Street": "Pick up the phone and start dialing!",
    "Black Panther": "Wakanda forever!",
    "The Social Network": "A milion dollars isn't cool. You know what is cool? A billion dollars.",
    "Harry Potter": "It is the quality of one's convictions that determines success, not the number of followers.",
    "The Dark Knight Rises": "A hero can be anyone. Even a man doing somethijng as simple and reassuring as putting a coat around a young boiy's shoulders to let him know the world hadn't ended.",
    "The Hobbit": "I've found it is the small things, everyday deeds or ordinary folk that keeps the darkness at bay.",
    "The Hunger Games": "Hope. It is the only thing stronger than fear.",
    "The Hunger Games": "May the odds be ever in your favor.",
    "Jurassic World": "The key to a happy life is to accept you are never actually in control.",
    "Deadpool": "Life is an endless series of train wrecks with only brief commercial-like breaks of happiness.",
    "Avengers": "The hardest choices reqire the strongest wills.",
    "Venom": "Eyes, lungs, pancreas. So many snacks, so little time.",
    "Avengers": "No amount of money ever bought a second of time.",
    "Harry Potter": "Do not pity the dead. Pity the living and, above all, those who live without love.",
    "The Other Guys": "At age 11, I audited my parents and believe me, there were some discrepancies. And I was grounded.",
    "Guardians of the Galaxy": "I am Groot.",
    "The Martian": "I don't want to come off as arrogant here, but I'm the greatest botanist on this planet.",
    "Her": "I think anybody who falls in love is a freak. It's a crazy thing to do. It's kind of like a form of socially acceptable insanity.",
    "Silver Linings Playbook": "The only way to beat my crazy was by doing something crazy yourself. Thank you. I love you.",
    "The Social Network": "You have part of my attention. You have the minimum amount.",
    "Wolf of Wall Street": "The year I turned 26, as the head of my own brokerage firm, I made 49 million dollars, which really pissed me off because it was just 3 shy of a million a week.",
    "Joker": "I used to think my life was a tragedy, but now I realize... It's a comedy.",
    "Get Him to the Greek": "Stroke the furry wall.",
    "The Irishman": "I heard you paint houses."
}
